In [2]:
import torch

In [3]:
torch.cuda.is_available()

True

In [5]:
torch.rand((2,3,4), device='cuda:0')

tensor([[[0.4989, 0.9486, 0.8340, 0.8356],
         [0.1435, 0.4324, 0.3002, 0.9863],
         [0.9927, 0.0665, 0.2224, 0.2728]],

        [[0.7193, 0.3206, 0.5103, 0.2828],
         [0.2984, 0.3128, 0.9230, 0.5881],
         [0.1405, 0.2288, 0.8392, 0.7252]]], device='cuda:0')

In [6]:
# move tensor to GPU
t = torch.rand((2,3,4))
t = t.to('cuda:0')
t

tensor([[[0.4018, 0.1252, 0.1411, 0.3493],
         [0.7988, 0.3571, 0.1489, 0.9517],
         [0.6101, 0.7708, 0.7718, 0.8431]],

        [[0.8939, 0.3156, 0.1905, 0.5762],
         [0.8283, 0.0888, 0.3868, 0.8343],
         [0.9205, 0.2711, 0.2710, 0.3458]]], device='cuda:0')

In [9]:
import numpy as np
a = np.random.rand(2,3)
t = torch.from_numpy(a) 

In [11]:
k = torch.rand((2,3,4)) 
k    
l = k.numpy()
l

array([[[0.28032136, 0.24476933, 0.8812768 , 0.8592284 ],
        [0.32251805, 0.7297166 , 0.0884853 , 0.43568188],
        [0.5468543 , 0.31218982, 0.2949018 , 0.11807251]],

       [[0.07930267, 0.57191384, 0.586196  , 0.11310858],
        [0.10362291, 0.0151971 , 0.31264365, 0.65390795],
        [0.08638966, 0.9936885 , 0.33296835, 0.55768013]]], dtype=float32)