In [1]:
import torch

In [ ]:
print(torch.__version__)

2.8.0+cpu


In [3]:
if torch.cuda.is_available():
    print("CUDA is available. Training on GPU.")    
else:
    print("CUDA is not available. Training on CPU.")    

CUDA is not available. Training on CPU.


Createing a tensor

In [6]:
# Using empty
a = torch.empty(2,3)

In [7]:
type(a)

torch.Tensor

In [8]:
# using zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
# using rand
torch.rand(2,3)

tensor([[0.6685, 0.5515, 0.4721],
        [0.6274, 0.0142, 0.1453]])

In [ ]:
# use of seed
torch.manual_seed(101)
torch.rand(2,3)

In [13]:
# using tensor
torch.tensor([[5,4,2],[54,32, 4]])

tensor([[ 5,  4,  2],
        [54, 32,  4]])

## Tensor SHape

In [14]:
x = torch.tensor([[5,4,2],[54,32, 4]])
x.shape

torch.Size([2, 3])

In [16]:
y = torch.empty_like(x)

## Tensor Data type

In [18]:
x.dtype

torch.int64

In [19]:
torch.tensor([1.5, 2.5, 4.3], dtype=torch.int32)

C:\Users\yuvra\AppData\Local\Temp\ipykernel_6456\585550531.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  torch.tensor([1.5, 2.5, 4.3], dtype=torch.int32)


tensor([1, 2, 4], dtype=torch.int32)

In [20]:
x.to(torch.float32)

tensor([[ 5.,  4.,  2.],
        [54., 32.,  4.]])